"""Emit the pgfplots data tables behind Figures 4 and 5.

Every coordinate in those two figures is written by this script from the result
files in results/; nothing in them is drawn by hand. Run it from the repository
root:

    python3 analysis/make_data_figures.py <output_dir>

It writes two whitespace-separated tables that the manuscript reads with
\\addplot table:

    controls.dat  -- the control-family figure (Figure 4 in the submitted
                     draft): every magnitude-matched control draw
    tradeoff.dat  -- the trade-off figure (Figure 5): avoidance against L2
                     and against collisions

Sources
    results/arm_metrics.json                per-horizon L2 and box-collision counts
    results/avoidance.json                  mean applied avoidance per arm
    results/mirror_control_*.json           reflected and negated controls
    results/rotation_control_*.json         uniform random rotation, 8 draws
    results/allocation_control_magnitude.json  permuted magnitude, 8 draws
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES = os.path.join(ROOT, "results")


def load(name):
    with open(os.path.join(RES, name)) as fh:
        return json.load(fh)


def write_table(path, header, rows):
    with open(path, "w") as fh:
        fh.write("# generated by analysis/make_data_figures.py -- do not edit\n")
        fh.write(" ".join(header) + "\n")
        for r in rows:
            fh.write(" ".join(str(x) for x in r) + "\n")
    print("wrote", path, "(%d rows)" % len(rows))


def figure4(out_dir):
    """Three arms: avoidance applied, headline L2, mean collision count.

    The x coordinate is the mean displacement the collision optimiser applied,
    which is zero by construction for the arm that has it switched off.
    """
    metrics = load("arm_metrics.json")["arms"]
    avoid = load("avoidance.json")["mean_over_horizons"]

    arms = [
        ("optimiser off", "R-0084_nocoloptim", 0.0),
        ("corrected", "R-0073_quantfix", avoid["corrected"]),
        ("published", "R-0072_baseline", avoid["published"]),
    ]
    rows = []
    for label, key, a in arms:
        m = metrics[key]
        rows.append([
            round(a, 4),
            round(m["avg_L2"], 4),
            round(m["mean_obj_box_col_count_over_6_horizons"], 2),
            label.replace(" ", "~"),
        ])
    write_table(os.path.join(out_dir, "tradeoff.dat"),
                ["avoid", "L2", "coll", "label"], rows)


# Two draws that land within this many cells of each other would print as one
# marker at the figure's scale, so they are offset vertically instead. The
# value is the marker diameter converted to data units for the axis geometry
# fixed in the manuscript (11.6 cm spanning 308 cells).
MIN_SEP_CELLS = 4.0
OFFSET_STEP = 0.30  # rows are 1.0 apart, so the largest offset stays inside one


def spread(values):
    """Offset coincident draws vertically so that all of them remain countable.

    The horizontal coordinate is never altered: only the vertical position
    within a categorical row changes, and that axis carries no meaning. Levels
    are assigned deterministically by ascending value, so re-running the script
    reproduces the figure exactly.
    """
    placed = []            # (value, level) already positioned
    out = []
    for v in sorted(values):
        level = 0
        while any(abs(v - pv) < MIN_SEP_CELLS for pv, pl in placed
                  if pl == level):
            level += 1
        placed.append((v, level))
        # level 0 on the row itself, then alternating above and below it
        sign = 1 if level % 2 else -1
        out.append((v, sign * OFFSET_STEP * ((level + 1) // 2)))
    return out


def figure5(out_dir):
    """Net repaired cells for each correction and each magnitude-matched control.

    Every sampled draw is one marker, so that "no draw of eight beat the real
    correction" is read off the plot rather than taken on trust. All counts are
    at the cell endpoint: `rotation_control_*.json` and `allocation_control.json`
    report the box-collision cell net, matching the `box` block of the mirror
    control files, so the whole figure is one endpoint throughout.
    """
    groups = [
        # (results file stem, row label for the correction, allocation control?)
        ("quantfix", "Defect 1: coordinate cast", True),
        ("egodiscs", "Defect 2: three discs (mean)", False),
        ("egodiscs_sum", "Defect 2: three discs (sum)", False),
    ]
    # One column per marker class, so a row carries its value in exactly one
    # column and `nan` in the rest; pgfplots then selects a class by column
    # name under `unbounded coords=discard`, with no string filtering.
    cols = ["real", "reflected", "negated", "random", "permuted", "allocref"]

    rows, yticks, headers, spans = [], [], [], []

    def emit(y, kind, value):
        rows.append([y] + [value if c == kind else "nan" for c in cols])

    def emit_draws(y, kind, values):
        for v, dy in spread(values):
            emit(round(y + dy, 2), kind, v)

    y = 12  # top row; groups are separated from each other by one blank row
    for stem, title, has_alloc in groups:
        mirror = load("mirror_control_%s.json" % stem)["box"]
        rot = load("rotation_control_%s.json" % stem)

        headers.append((y, mirror["arm"]["net"], title))

        emit(y, "real", mirror["arm"]["net"])
        yticks.append((y, "real correction")); y -= 1
        emit(y, "reflected", mirror["mirror"]["net"])
        yticks.append((y, "reflected")); y -= 1
        emit(y, "negated", mirror["neg"]["net"])
        yticks.append((y, "negated")); y -= 1
        emit_draws(y, "random", rot["rotated_net_per_draw"])
        yticks.append((y, "uniform random (8 draws)")); y -= 1
        if has_alloc:
            alloc = load("allocation_control_magnitude.json")
            emit_draws(y, "permuted", alloc["permuted_net_per_draw"])
            # the magnitude-matched allocation control is scored against the
            # direction-stripped reference f-hat, not against the corrected arm,
            # so plot that reference on the same row rather than borrowing the
            # real marker. (The earlier retention-permutation control is not
            # plotted: it is confounded and withdrawn -- see the paper.)
            emit(y, "allocref", alloc["real_allocation_net"])
            yticks.append((y, "permuted magnitude (8 draws)")); y -= 1
        spans.append(y + 1)  # last row this group occupies
        y -= 1  # blank separator row between groups

    write_table(os.path.join(out_dir, "controls.dat"), ["y"] + cols, rows)

    # The row positions above are computed, not chosen, so the axis description
    # is generated with them rather than restated by hand in the manuscript.
    axis = os.path.join(out_dir, "controls_axis.tex")
    with open(axis, "w") as fh:
        fh.write("% generated by analysis/make_data_figures.py -- do not edit\n")
        # Labels stay plain ASCII: pgfkeys expands this macro while parsing
        # the option list, and a control sequence such as \times inside a
        # tick label fails there with "Missing \\endcsname".
        # One macro holding the whole key list: pgfkeys expands a macro used as
        # a complete option list, but does NOT expand one supplied as a single
        # key's value, so `yticklabels=\macro' would typeset the list as text.
        fh.write("\\def\\controlsymin{%.1f}\n" % (yticks[-1][0] - 1.0))
        fh.write("\\def\\controlsymax{%.1f}\n" % (yticks[0][0] + 0.9))
        fh.write("\\def\\controlsaxis{%%\n"
                 "  ymin=%.1f, ymax=%.1f,\n"
                 "  ytick={%s},\n"
                 "  yticklabels={%s}}\n"
                 % (yticks[-1][0] - 1.0, yticks[0][0] + 0.9,
                    ",".join(str(t) for t, _ in yticks),
                    ",".join("{%s}" % lab for _, lab in yticks)))
        # emitted as calls rather than a comma list, so a title may contain
        # commas without breaking \foreach parsing on the LaTeX side
        fh.write("\\def\\controlsheaders{%s}\n"
                 % "".join("\\ctrlhdr{%d}{%s}{%s}" % (t, n, lab)
                           for t, n, lab in headers))
        # the dashed line that carries each correction's score down through its
        # own control rows, so "no draw beat it" is read off the plot
        fh.write("\\def\\controlsrefs{%s}\n"
                 % "".join("\\ctrlref{%s}{%.1f}{%.1f}"
                           % (n, t + 0.45, span + -0.45)
                           for (t, n, _), span in zip(headers, spans)))
    print("wrote", axis)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(out_dir, exist_ok=True)
    figure4(out_dir)
    figure5(out_dir)


if __name__ == "__main__":
    main()
